# Generated by Django 5.1.2 on 2024-10-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Наличными'), ('Transfer', 'Перевод на счёт')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
