# Generated by Django 5.1.2 on 2024-10-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
